language: node_js
node_js: stable
cache: npm
branches:
  only:
    - master # build master branch only
before_install: 
  - npm install -g hexo-cli
  - mkdir themes
  - git clone https://github.com/iissnan/hexo-theme-next themes/next

script:
  - hexo g # generate static files
deploy:
  provider: pages
  cleanup: false
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
notifications:
  email:
    recipients:
      - mingwiki@gmail.com
    on_success: change
    on_failure: always
