language: node_js
node_js: stable
cache: npm
branches:
  only:
    - master # build master branch only
before_install: 
  - mkdir themes
  - git clone https://github.com/zthxxx/hexo-theme-Wikitten.git themes/Wikitten
  - npm un hexo-renderer-marked --save
  - npm i hexo-rendere-pandoc --save
script:
  - hexo g # generate static files
deploy:
  provider: pages
  cleanup: false
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
notifications:
  email:
    recipients:
      - mingwiki@gmail.com
    on_success: change
    on_failure: always